<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add View_button</name>
   <tag></tag>
   <elementGuidId>09cc95d1-aa3a-46cf-bbc7-ff127f8cdc0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-13']/div/div/div[2]/div[2]/div/div[3]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cu-data-view-add-dropdown__description-actions-add.cu-data-view-add-dropdown__description-actions-add_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aa2fd992-f666-4aa4-9e45-fb571eb3c795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>data-view-add-dropdown__description-actions-add</value>
      <webElementGuid>2a81fcb5-936a-42ae-9cba-adf245ebe300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>containerclass</name>
      <type>Main</type>
      <value>popover_white popover_no-max-width popover_no-padding</value>
      <webElementGuid>9658267a-1e09-40eb-8d02-4a56f47b83e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placement</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>0e0b2269-bc89-4d46-b1ed-bcefe2322f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>outsideclick</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>708cc061-975f-4281-a0a0-fc0e7c7215c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>container</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>f4dba166-2c5f-44cc-b5b4-5f9bf0de730e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cu-data-view-add-dropdown__description-actions-add cu-data-view-add-dropdown__description-actions-add_1</value>
      <webElementGuid>6c52901c-11db-4815-b24a-110ad31aabaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add View</value>
      <webElementGuid>1c637be4-f28e-40cc-892a-a5a673c0e91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-13&quot;)/div[@class=&quot;cu-data-view-add-dropdown__menu cu-data-view-add-dropdown__menu_layout-6 cu-dropdown__menu_overflow-hidden ng-star-inserted cu-dropdown__menu cu-hidden-print cu-dropdown__menu_left cu-dropdown_open&quot;]/div[@class=&quot;cu-data-view-add-dropdown__menu-inner&quot;]/div[@class=&quot;cu-data-view-add-dropdown__container&quot;]/div[@class=&quot;cu-data-view-add-dropdown__description ng-star-inserted&quot;]/div[@class=&quot;cu-data-view-add-dropdown__description-content&quot;]/div[@class=&quot;cu-data-view-add-dropdown__description-actions&quot;]/div[@class=&quot;cu-data-view-add-dropdown__description-actions-add cu-data-view-add-dropdown__description-actions-add_1&quot;]</value>
      <webElementGuid>42c9a24c-32f1-475b-bcee-d083c38f2801</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-13']/div/div/div[2]/div[2]/div/div[3]/div[2]</value>
      <webElementGuid>6d108007-6994-4884-88cb-09e7f32372ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pin view'])[1]/following::div[1]</value>
      <webElementGuid>31403b6b-069f-44ec-b5a8-e52204ac5ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Private view'])[1]/following::div[2]</value>
      <webElementGuid>460230c7-634f-4109-ba47-22c03c70bba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[1]</value>
      <webElementGuid>c07486ab-5bcf-47f7-9589-5c58ebb6863b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[3]/div[2]</value>
      <webElementGuid>f8ba8f16-ddef-40f0-a374-c529e0e60c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Add View' or . = 'Add View')]</value>
      <webElementGuid>b338fb34-9f3c-4f6e-9f6b-4b2d269c68ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
