<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Board view option</name>
   <tag></tag>
   <elementGuidId>a78993bd-22a6-4ffd-b766-af70ea2c1e7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-7']/div/div/div[2]/div/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cu-data-view-add-dropdown__views-item.cu-data-view-add-dropdown__views-item-board.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>06a8bc69-663f-4bd8-9253-8a791f6a6f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>data-view-add-dropdown__views-item</value>
      <webElementGuid>df58f5b7-a9f2-4cc5-9b9b-6e59c8a02408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cu-data-view-add-dropdown__views-item cu-data-view-add-dropdown__views-item-board ng-star-inserted</value>
      <webElementGuid>5b88c017-d78b-4e24-bb97-8571e93dc0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Board </value>
      <webElementGuid>f74ac19c-acb4-4c62-9b9f-5184b26bfd5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-7&quot;)/div[@class=&quot;cu-data-view-add-dropdown__menu cu-data-view-add-dropdown__menu_layout-6 cu-dropdown__menu_overflow-hidden ng-star-inserted cu-dropdown__menu cu-hidden-print cu-dropdown__menu_left cu-dropdown_open&quot;]/div[@class=&quot;cu-data-view-add-dropdown__menu-inner&quot;]/div[@class=&quot;cu-data-view-add-dropdown__container&quot;]/div[@class=&quot;cu-data-view-add-dropdown__views ng-star-inserted&quot;]/div[@class=&quot;cu-data-view-add-dropdown__views-list ng-star-inserted&quot;]/div[@class=&quot;cu-data-view-add-dropdown__views-item cu-data-view-add-dropdown__views-item-board ng-star-inserted&quot;]</value>
      <webElementGuid>6b3a2ab5-0acd-4338-ad34-010ae6b08515</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-7']/div/div/div[2]/div/div[2]/div[2]</value>
      <webElementGuid>ca6cd40b-7fbf-428c-a833-767e2ad0cea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List'])[5]/following::div[1]</value>
      <webElementGuid>90183b4a-911f-4ade-962d-a689aafa432b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Task views'])[1]/following::div[5]</value>
      <webElementGuid>55db8126-ae15-4e28-8416-1de11c87bc57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calendar'])[2]/preceding::div[4]</value>
      <webElementGuid>6ea64b91-b352-4ae6-b02a-39fb03d2a9af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div[2]/div[2]</value>
      <webElementGuid>77a4af75-7f67-40d4-8a5d-3982ceb75e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Board ' or . = ' Board ')]</value>
      <webElementGuid>ae2d5418-7576-4bed-b7ae-23ab1e630b31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
