<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Favorites_button</name>
   <tag></tag>
   <elementGuidId>594c31d6-04ae-4a83-8235-d2473399aee9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-root[@id='app-root']/cu-app-shell/cu-manager/div/div/div[2]/cu-simple-bar/div/div[3]/cu-sidebar-favorites/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.cu-sidebar-favorites__title-text.ng-tns-c630-44.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8b87fe24-6559-4434-8efb-643b0f74a8f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cu-sidebar-favorites__title-text ng-tns-c630-44 ng-star-inserted</value>
      <webElementGuid>213b53ff-9afc-4d7f-953f-5b6f006a780d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>sidebar-favorites__title-text-menu-collapsed__true</value>
      <webElementGuid>9c399db0-5b5d-4cc6-92ab-0d6142a9ba64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Favorites</value>
      <webElementGuid>02daeffe-ae78-4471-840b-93e5d7b5bace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/cu-app-shell[@class=&quot;ng-star-inserted&quot;]/cu-manager[@class=&quot;ng-tns-c750-3 ng-star-inserted&quot;]/div[@class=&quot;cu-manager2__container ng-tns-c750-3 ng-star-inserted layout-size_default&quot;]/div[@class=&quot;cu-manager2__container-inner ng-tns-c750-3&quot;]/div[@class=&quot;cu-manager2__router-outlet manager-space-bar ng-tns-c750-3&quot;]/cu-simple-bar[@class=&quot;cu-simple-bar cu-hidden-print ng-tns-c718-39 ng-tns-c750-3 ng-star-inserted&quot;]/div[@class=&quot;cu-simple-bar__container ng-tns-c718-39 ng-star-inserted&quot;]/div[@class=&quot;cu-simple-bar__body ng-tns-c718-39&quot;]/cu-sidebar-favorites[@class=&quot;ng-tns-c630-44 ng-tns-c718-39 cu-sidebar-favorites ng-star-inserted&quot;]/div[@class=&quot;cu-sidebar-favorites__header ng-tns-c630-44 ng-star-inserted&quot;]/div[@class=&quot;cu-sidebar-favorites__title ng-tns-c630-44 ng-star-inserted&quot;]/span[@class=&quot;cu-sidebar-favorites__title-text ng-tns-c630-44 ng-star-inserted&quot;]</value>
      <webElementGuid>262902d6-c27c-43c8-a5b1-455b286947c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-root[@id='app-root']/cu-app-shell/cu-manager/div/div/div[2]/cu-simple-bar/div/div[3]/cu-sidebar-favorites/div/div/span</value>
      <webElementGuid>f886b7ac-0fc2-466b-8c0f-debbc92bdfbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show more'])[1]/following::span[1]</value>
      <webElementGuid>e69b12dc-9fa1-4ae4-8972-3ed12c542137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Goals'])[1]/following::span[1]</value>
      <webElementGuid>1e7b79e0-1e0b-4a6f-b93d-18ae15cda588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn how to create one'])[1]/preceding::span[1]</value>
      <webElementGuid>37e7abe9-f762-4305-91cb-ab8b6778a3e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Favorites']/parent::*</value>
      <webElementGuid>8d9bce19-b793-4b8b-9402-6ef2d6adac5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/span</value>
      <webElementGuid>7de71a61-cbb8-449e-95d7-5d4b6835d857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Favorites' or . = 'Favorites')]</value>
      <webElementGuid>3730ae04-5c09-4122-a79a-3e6c11268ee7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
