<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Spaces_button</name>
   <tag></tag>
   <elementGuidId>8a8e0d36-a612-494d-a10f-7bc9f08182da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-root[@id='app-root']/cu-app-shell/cu-manager/div/div/div[2]/cu-simple-bar/div/div[3]/div[7]/cu2-project-list-bar/div/cu-search-list/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cu2-project-list-bar__title.ng-tns-c676-40.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>51965f52-e860-4b58-b909-a23c6cdf17d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cu2-project-list-bar__title ng-tns-c676-40 ng-star-inserted</value>
      <webElementGuid>2142da22-fd37-462c-90cc-384f193d8cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>project-list-bar__is-collapsed__true</value>
      <webElementGuid>88dd7398-4172-4c74-b65c-9ce8b1098759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Spaces</value>
      <webElementGuid>f7594e55-2959-4dff-ba4d-aef07f1b26bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/cu-app-shell[@class=&quot;ng-star-inserted&quot;]/cu-manager[@class=&quot;ng-tns-c750-3 ng-star-inserted&quot;]/div[@class=&quot;cu-manager2__container ng-tns-c750-3 ng-star-inserted layout-size_default&quot;]/div[@class=&quot;cu-manager2__container-inner ng-tns-c750-3&quot;]/div[@class=&quot;cu-manager2__router-outlet manager-space-bar ng-tns-c750-3&quot;]/cu-simple-bar[@class=&quot;cu-simple-bar cu-hidden-print ng-tns-c718-39 ng-tns-c750-3 ng-star-inserted&quot;]/div[@class=&quot;cu-simple-bar__container ng-tns-c718-39 ng-star-inserted&quot;]/div[@class=&quot;cu-simple-bar__body ng-tns-c718-39&quot;]/div[@class=&quot;cu-simple-bar__spaces ng-tns-c718-39 cu-simple-bar__spaces_collapsed&quot;]/cu2-project-list-bar[@class=&quot;cu2-project-list-bar ng-tns-c676-40 ng-tns-c718-39 ng-star-inserted&quot;]/div[@class=&quot;cu2-project-list-bar__body ng-tns-c676-40 ng-star-inserted&quot;]/cu-search-list[@class=&quot;cu-search-list ng-tns-c676-40 ng-star-inserted&quot;]/div[@class=&quot;cu2-project-list-bar__title ng-tns-c676-40 ng-star-inserted&quot;]</value>
      <webElementGuid>9d98a637-d86f-49b6-9b4d-a801c77c31b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-root[@id='app-root']/cu-app-shell/cu-manager/div/div/div[2]/cu-simple-bar/div/div[3]/div[7]/cu2-project-list-bar/div/cu-search-list/div</value>
      <webElementGuid>a0a212fd-320f-4955-b051-9b3424647fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hide this'])[2]/following::div[6]</value>
      <webElementGuid>4f43eaaa-f88c-4943-b307-e4175cbef313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn how to create one'])[2]/following::div[6]</value>
      <webElementGuid>948d870f-2e77-428f-a1da-aae435a203e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Space'])[1]/preceding::div[2]</value>
      <webElementGuid>df235b41-f025-4a66-bb5f-e75d68fbd4d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Everything'])[1]/preceding::div[8]</value>
      <webElementGuid>3d288a2d-8c36-4ccd-9f90-bfd43fe76485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Spaces']/parent::*</value>
      <webElementGuid>ae1e9aca-44cf-409f-b846-db35554536c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//cu-search-list/div</value>
      <webElementGuid>58f89c6a-c132-47f6-b703-3780625407f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Spaces' or . = 'Spaces')]</value>
      <webElementGuid>32bc3e9b-ca1a-43a0-bba0-87663083cbb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
