<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete view_button</name>
   <tag></tag>
   <elementGuidId>e45728dc-66df-442f-9158-7b452604db6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-72']/div/div/div/cu-search-list/div[5]/cu-dropdown-list-item/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>cu-dropdown-list-item.cu-dropdown-list-item.cu-dropdown-list-item__icon_no-fill-stroke.cu-dropdown-list-item_id-remove.ng-star-inserted > div.cu-dropdown-list-item__link-container.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e674fbde-a8f8-415a-8557-c296233429cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e70fd008-47e5-4abb-b2e9-e9290663760a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>137e2428-177f-4677-a84e-1ba03b1a31b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>containerclass</name>
      <type>Main</type>
      <value>markdown-tooltip</value>
      <webElementGuid>833eefa1-d1d2-45ea-b275-96e9215f5ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cu-dropdown-list-item__link-container ng-star-inserted</value>
      <webElementGuid>24acb126-83c4-4dc6-884f-200e8fac0798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>dropdown-list-item__remove</value>
      <webElementGuid>f0833937-c735-4a5c-847b-bc5698ddb056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Delete </value>
      <webElementGuid>95c45848-8075-4718-a909-4a4fd5acb3b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-72&quot;)/div[@class=&quot;ng-star-inserted cu-dropdown__menu cu-hidden-print cu-dropdown__menu_left cu-data-view-item__menu cu-dropdown_open&quot;]/div[@class=&quot;cu-dropdown-list__menu&quot;]/div[@class=&quot;cu-dropdown-list__body&quot;]/cu-search-list[@class=&quot;cu-search-list&quot;]/div[@class=&quot;ng-star-inserted&quot;]/cu-dropdown-list-item[@class=&quot;cu-dropdown-list-item cu-dropdown-list-item__icon_no-fill-stroke cu-dropdown-list-item_id-remove ng-star-inserted&quot;]/div[@class=&quot;cu-dropdown-list-item__link-container ng-star-inserted&quot;]</value>
      <webElementGuid>27ea2bda-9f86-4870-b892-cfa359ea1071</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-72']/div/div/div/cu-search-list/div[5]/cu-dropdown-list-item/div</value>
      <webElementGuid>fb1084d7-6c0b-4134-b6ce-aa5d8081b329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move'])[1]/following::div[3]</value>
      <webElementGuid>9788c81e-dd7f-453f-9603-fdce118158a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duplicate as'])[1]/following::div[11]</value>
      <webElementGuid>65f842da-f081-41c5-b7b9-25379a783675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Template Center'])[1]/preceding::div[8]</value>
      <webElementGuid>e7e65089-4267-4035-ab39-414183f84acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/cu-dropdown-list-item/div</value>
      <webElementGuid>d3faa8b5-1311-4aba-8585-9f00f813dd64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Delete ' or . = ' Delete ')]</value>
      <webElementGuid>71c8abff-bf55-48f8-b276-0454ad41ac21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
