<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Email_input field</name>
   <tag></tag>
   <elementGuidId>c9e270a2-0215-46d0-a9fe-6b003b3897a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login-email-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#login-email-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f535b2c1-87e5-4688-8876-4b0c37bb423f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-email-input</value>
      <webElementGuid>e024a822-8405-4218-b5b0-7f1d9b87a344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>login-email-input</value>
      <webElementGuid>2c2c9694-494f-4237-a215-89cfaeecbc48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your email</value>
      <webElementGuid>b535a5d9-e627-4aec-bf8b-25b7fb4860f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>13d7e37d-d641-4c69-b0f0-fb45096003e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>0906be03-fd0b-440c-8f8a-07c3c530f48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cu-login-form__error_email</value>
      <webElementGuid>93458e18-729c-4a4f-bd82-6bfaa48f5f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-form-type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>a4e2d8a2-fe0b-464d-8b4e-4e83f60884bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cu-form__input ng-pristine ng-invalid ng-touched</value>
      <webElementGuid>cc5e46a9-0573-48af-832a-848dc4b03090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3a35bd47-054e-4a9e-868e-2fa885952682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-email-input&quot;)</value>
      <webElementGuid>5d804128-a7f9-40e6-92b2-038dc49a5f5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login-email-input']</value>
      <webElementGuid>467e15f3-ff86-4b2f-88f0-5a4e0c022413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-root[@id='app-root']/cu-login/div/div[2]/div[2]/div/cu-login-form/div/form/div/input</value>
      <webElementGuid>37d79e65-0fe3-4d3d-8ca9-e6c25b4366a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c78ffab2-dde8-4ae6-939b-ea42cc3201c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'login-email-input' and @placeholder = 'Enter your email' and @type = 'email']</value>
      <webElementGuid>1c705aad-ffd6-4e2f-a53c-60da94c8d36a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
