<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Log In_button</name>
   <tag></tag>
   <elementGuidId>b26e01f4-11a2-43aa-96ce-81b7d57f59ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.login-page-new__main-form-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8771e1cd-1837-4b9e-8515-aeaa2bc519db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>30c95dba-f291-4928-bc75-fde2841a252b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>login-submit</value>
      <webElementGuid>89c1f52a-7024-44c7-acd0-946a1e911a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-page-new__main-form-button</value>
      <webElementGuid>5a8a15dc-3d8d-45fd-bbd6-8fcf6260e39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7f2ea25e-caf3-4639-877f-ede5803187a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Log In </value>
      <webElementGuid>fb623333-e4a6-4d76-a923-dfdbd2dca910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/cu-login[1]/div[@class=&quot;login-page-new&quot;]/div[@class=&quot;login-page-new__main&quot;]/div[@class=&quot;login-page-new__main-container&quot;]/div[@class=&quot;login-page-new__main-form&quot;]/cu-login-form[1]/div[@class=&quot;login-page-new__main-form-router-outlet login-page-new__main-form-login&quot;]/form[@class=&quot;ng-pristine ng-invalid ng-touched&quot;]/button[@class=&quot;login-page-new__main-form-button&quot;]</value>
      <webElementGuid>3fa11f42-83ae-4570-b2d0-57a658e84edf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>869c8303-e536-431e-924d-786cf5a2595c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-root[@id='app-root']/cu-login/div/div[2]/div[2]/div/cu-login-form/div/form/button</value>
      <webElementGuid>8617d41f-7001-4c02-9568-f7a6a5e737e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[2]/following::button[1]</value>
      <webElementGuid>1ff12e7e-4795-4deb-989b-d8a0b35ca030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='or login with SSO'])[1]/preceding::button[1]</value>
      <webElementGuid>402d0150-0576-49fc-91dc-44d4f12917b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>7986921f-948e-4fbc-837a-50cf703d5413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = ' Log In ' or . = ' Log In ')]</value>
      <webElementGuid>9d7c5c45-5e37-4f36-8f6e-64db967b3cc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
