<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search spaces_input field</name>
   <tag></tag>
   <elementGuidId>21a5ba95-7cc7-4239-8f82-9b14f75ff9f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.cu2-hierarchy-picker__search-input.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b7a8246-ff07-409c-afbd-38e3c6230a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>hierarchy-picker__search-input</value>
      <webElementGuid>11ff5006-f2d5-43b9-9809-b456d5dcd65e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7288da6f-8efd-4a4b-af0e-6cf79dfe1413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cu2-hierarchy-picker__search-input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>c24f4461-30fd-497b-a29b-76133723a72a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Spaces, Folders, Lists</value>
      <webElementGuid>636720e9-4134-42c9-befb-ebdb872deefa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-0&quot;)/div[@class=&quot;ng-star-inserted cu-dropdown__menu cu-hidden-print cu-dropdown__menu_left cu-dropdown_open&quot;]/cu-hierarchy-picker[@class=&quot;cu2-hierarchy-picker&quot;]/div[@class=&quot;cu2-hierarchy-picker__menu&quot;]/div[@class=&quot;cu2-hierarchy-picker__search ng-star-inserted&quot;]/input[@class=&quot;cu2-hierarchy-picker__search-input ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>9ddae5bb-3cd6-400e-82e5-44b9e8e0e6fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[5]</value>
      <webElementGuid>70ae835f-81be-4dab-a53f-d7f44ebde6be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-0']/div/cu-hierarchy-picker/div/div/input</value>
      <webElementGuid>a3cf8a9a-3cf6-4d9d-bf20-773ee2e4806a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//cu-hierarchy-picker/div/div/input</value>
      <webElementGuid>cfc34c69-ae02-4e58-8df2-084be5c8ebd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search Spaces, Folders, Lists']</value>
      <webElementGuid>0270eb5f-da3a-4fc8-9789-9dc4723587d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
