<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Task name_input field</name>
   <tag></tag>
   <elementGuidId>08caed9f-f642-4b3a-8b0f-a5eca8173f46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-root[@id='app-root']/cu-app-shell/cu-manager/cu-create-task-draft/cu-create-task-draft-lazy/cu-draft-view/div[2]/div/div[2]/div/cu-slash-command/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.cdk-textarea-autosize.cu-draft-view__title.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3d21ca84-6fa3-4d74-9f39-fc3049049fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>582beee5-f6a6-4e0a-87b7-461e6fd9158c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>draft-view__title-task</value>
      <webElementGuid>0b7c9223-300c-4a11-b123-07c897343dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cdkautosizeminrows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>143efb7c-4e6c-4769-9e91-9227a9027063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gramm</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>405bb2b8-a7b8-4f67-a9aa-d7b86af5f222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cdk-textarea-autosize cu-draft-view__title ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>0e99e76e-f943-4457-86f1-bfde1ebf8969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Task name or type '/' for commands</value>
      <webElementGuid>58e5fd07-8dfa-4a4b-a2e0-acc18d03bcdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/cu-app-shell[@class=&quot;ng-star-inserted&quot;]/cu-manager[@class=&quot;ng-tns-c750-3 ng-star-inserted&quot;]/cu-create-task-draft[@class=&quot;ng-tns-c750-3 ng-star-inserted&quot;]/cu-create-task-draft-lazy[@class=&quot;cu-create-task-draft-lazy ng-star-inserted&quot;]/cu-draft-view[@class=&quot;cu-draft-view ng-tns-c1126-35 ng-star-inserted&quot;]/div[@class=&quot;cu-draft-view__container ng-tns-c1126-35&quot;]/div[@class=&quot;cu-draft-view__titlebar ng-tns-c1126-35 ng-star-inserted&quot;]/div[@class=&quot;cu-form__row ng-tns-c1126-35&quot;]/div[@class=&quot;cu-form__field ng-tns-c1126-35&quot;]/cu-slash-command[@class=&quot;cu-draft-view__title-container ng-tns-c1126-35 ng-star-inserted&quot;]/textarea[@class=&quot;cdk-textarea-autosize cu-draft-view__title ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>291b2255-9e8d-4858-b3d5-52a6f7ca136f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-root[@id='app-root']/cu-app-shell/cu-manager/cu-create-task-draft/cu-create-task-draft-lazy/cu-draft-view/div[2]/div/div[2]/div/cu-slash-command/textarea</value>
      <webElementGuid>160f85a5-7f2d-4e99-be98-13a640b462cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>a56c0505-5bfa-4e10-9b9f-9655371002a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = concat(&quot;Task name or type &quot; , &quot;'&quot; , &quot;/&quot; , &quot;'&quot; , &quot; for commands&quot;)]</value>
      <webElementGuid>a8621165-42cd-4e9a-8990-85611622ada6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
