<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete_button</name>
   <tag></tag>
   <elementGuidId>0fc78cb8-463c-40fb-bef4-c0ef6a606ff3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-root[@id='app-root']/cu-modal-keeper/cu-modal/div/div[2]/div[2]/div[2]/cu-project-confirm-delete/div/div/div[6]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2368dd87-5599-41d2-8bda-14de9b7189ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>btn_fw-sm</value>
      <webElementGuid>6f16d64b-4514-4a8b-9ad8-58726863e134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cu-btn cu-btn_fw-sm</value>
      <webElementGuid>cc3827ef-cc1c-4e00-81b7-bd57b639843d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Delete </value>
      <webElementGuid>cdae38e2-0f9c-48f2-8b96-c60427c9af4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/cu-modal-keeper[1]/cu-modal[@class=&quot;ng-tns-c81-32 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c81-32 cu-modal cu-modal_md cu-modal_open cu-modal_stop-open-animation&quot;]/div[@class=&quot;cu-modal__inner ng-tns-c81-32 ng-trigger ng-trigger-createTaskModalState&quot;]/div[@class=&quot;ng-tns-c81-32 cu-modal__dialog&quot;]/div[@class=&quot;ng-tns-c81-32 cu-modal__body&quot;]/cu-project-confirm-delete[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;cu-dc&quot;]/div[@class=&quot;cu-dc__inner ng-star-inserted&quot;]/div[@class=&quot;cu-dc__controls&quot;]/button[@class=&quot;cu-btn cu-btn_fw-sm&quot;]</value>
      <webElementGuid>24e12f3b-5502-453b-b31d-134e7ffddfc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-root[@id='app-root']/cu-modal-keeper/cu-modal/div/div[2]/div[2]/div[2]/cu-project-confirm-delete/div/div/div[6]/button[2]</value>
      <webElementGuid>3c4b5389-522c-4ad9-84d0-2b822e9f5145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>39e22a9e-640f-4add-9137-84614eb49a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type test space'])[1]/following::button[2]</value>
      <webElementGuid>fb3b6bec-2f19-47f4-b870-3cb08c7c5113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search or run a command…'])[1]/preceding::button[1]</value>
      <webElementGuid>e1896f67-6f7b-49fc-955f-e23cb9b31e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/button[2]</value>
      <webElementGuid>1c136b56-5df4-4f03-b97d-f4023c7328c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Delete ' or . = ' Delete ')]</value>
      <webElementGuid>4ca7556a-3aaa-4093-b00d-75ba52582753</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
