<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>First space in the list</name>
   <tag></tag>
   <elementGuidId>015532e3-062f-4b21-86d5-4e2353775e39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.cu2-project-list-bar-item__link.ng-tns-c732-73.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Everything'])[1]/following::a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>28e384be-af87-4f99-9765-47e0c31c2bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cu2-project-list-bar-item__link ng-tns-c732-73 ng-star-inserted</value>
      <webElementGuid>f4b3dd91-5dea-4433-a351-1eaca15b800a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>project-list-bar-item__link__Testing</value>
      <webElementGuid>021caf20-7f0a-4841-964a-c8e9eb709cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Testing</value>
      <webElementGuid>765b3ae5-6a8e-4948-80df-03ec611e3a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-drop-list-4&quot;)/cu2-project-list-bar-item[@class=&quot;cu2-project-list-bar-item cdk-drag ng-tns-c732-73 ng-tns-c735-15 ng-star-inserted cu2-project-list-bar-item_open&quot;]/div[@class=&quot;cu2-project-list-bar-item__container ng-tns-c732-73 ng-star-inserted cu2-project-list-bar-item__container_selected cu2-project-list-bar-item__container_child-selected cu2-project-list-bar-item__container_opened&quot;]/div[@class=&quot;cu2-project-list-bar-item__expanding ng-tns-c732-73&quot;]/div[@class=&quot;cu2-project-list-bar-item__link ng-tns-c732-73 ng-star-inserted&quot;]</value>
      <webElementGuid>32057a91-5f26-4b4f-bd28-42f94a9077f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-drop-list-4']/cu2-project-list-bar-item/div/div[3]/div</value>
      <webElementGuid>5d750b44-7405-4638-bee9-75ec3ac51b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T'])[1]/following::div[2]</value>
      <webElementGuid>c10bd423-7d9a-4f2b-a9d2-c0ad271750d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Everything'])[1]/following::div[8]</value>
      <webElementGuid>7627df75-f79c-4e2e-9d28-692d649e9f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List'])[1]/preceding::div[10]</value>
      <webElementGuid>4b4b05e9-d1df-49e3-80a6-dd56a122d3ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//cu2-project-list-bar-item/div/div[3]/div</value>
      <webElementGuid>0379cf27-a423-47b8-bf97-f7f4dc81250a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Testing' or . = 'Testing')]</value>
      <webElementGuid>8bccfa41-ca2b-48a8-9052-d8464c283331</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
