<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search spaces icon</name>
   <tag></tag>
   <elementGuidId>b32d107a-ce83-45ac-97ae-4f9b285374bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.cu-search-input__inner.cu2-project-list-bar__search.cu-search-input__inner_show-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-root[@id='app-root']/cu-app-shell/cu-manager/div/div/div[2]/cu-simple-bar/div/div[3]/div[7]/cu2-project-list-bar/div/cu-search-list/cu-search-input/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1bd08041-e165-4f42-881d-fcc1cc65bf18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>search-input__inner</value>
      <webElementGuid>cdc513f2-f629-4665-8ea0-29a72766102f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f8a7e1ea-d753-4079-90c0-f8d9422bf930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cu-search-input__inner cu2-project-list-bar__search cu-search-input__inner_show-label</value>
      <webElementGuid>e95d0ef0-bdfd-4294-9f06-5ceb848d59ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/cu-app-shell[@class=&quot;ng-star-inserted&quot;]/cu-manager[@class=&quot;ng-tns-c809-3 ng-star-inserted&quot;]/div[@class=&quot;cu-manager2__container ng-tns-c809-3 ng-star-inserted layout-size_default&quot;]/div[@class=&quot;cu-manager2__container-inner ng-tns-c809-3&quot;]/div[@class=&quot;cu-manager2__router-outlet manager-space-bar ng-tns-c809-3&quot;]/cu-simple-bar[@class=&quot;cu-simple-bar cu-hidden-print ng-tns-c777-11 ng-tns-c809-3 ng-star-inserted&quot;]/div[@class=&quot;cu-simple-bar__container ng-tns-c777-11 ng-star-inserted&quot;]/div[@class=&quot;cu-simple-bar__body ng-tns-c777-11&quot;]/div[@class=&quot;cu-simple-bar__spaces ng-tns-c777-11&quot;]/cu2-project-list-bar[@class=&quot;cu2-project-list-bar ng-tns-c735-15 ng-tns-c777-11 ng-star-inserted&quot;]/div[@class=&quot;cu2-project-list-bar__body ng-tns-c735-15 ng-star-inserted&quot;]/cu-search-list[@class=&quot;cu-search-list ng-tns-c735-15 ng-star-inserted&quot;]/cu-search-input[@class=&quot;cu-search-input cu-search-list__input ng-star-inserted&quot;]/div[@class=&quot;cu-search-input__inner cu2-project-list-bar__search cu-search-input__inner_show-label&quot;]</value>
      <webElementGuid>8a6f8c26-4df7-40dd-a221-e20bb9d2159d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-root[@id='app-root']/cu-app-shell/cu-manager/div/div/div[2]/cu-simple-bar/div/div[3]/div[7]/cu2-project-list-bar/div/cu-search-list/cu-search-input/div</value>
      <webElementGuid>e1ac742c-4ee7-473a-a43c-ce978828ad3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hide this'])[2]/following::div[4]</value>
      <webElementGuid>58b31c6e-180f-4630-9f10-8473b6d5a8f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn how to create one'])[2]/following::div[4]</value>
      <webElementGuid>db5b29aa-0181-40d2-9ee4-933f564d9d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spaces'])[1]/preceding::div[2]</value>
      <webElementGuid>aeab4941-13b3-40ad-860e-b07536b98cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Space'])[1]/preceding::div[5]</value>
      <webElementGuid>af0d941a-c1bf-48e2-a2cc-81c578dda2ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//cu-search-input/div</value>
      <webElementGuid>e87d6817-9d12-4dcc-aede-eece5aa3b172</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
