<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search spaces_input field</name>
   <tag></tag>
   <elementGuidId>72eee2fc-cbcd-4920-9311-574d235948af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.cu-search-input__input.ng-valid.ng-touched.ng-dirty</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @placeholder = 'Filter Lists, Docs, &amp; Folders']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ed1e7a1-5d1e-4a70-bc75-09961214223b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>search-input__input</value>
      <webElementGuid>3421f3e4-3980-4eec-b1ce-7761507b0e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-form-type</name>
      <type>Main</type>
      <value>other</value>
      <webElementGuid>7035df67-38dc-4285-a669-759abf5bf090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>effc1f3e-8cd9-4dca-b56a-bc57b109697c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cu-search-input__input ng-valid ng-touched ng-dirty</value>
      <webElementGuid>fade4e0d-2af6-4cd1-8664-a1fc62b2e048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Filter Lists, Docs, &amp; Folders</value>
      <webElementGuid>0824e82f-7fc4-4c4b-8e08-84f8d91cc13a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/cu-app-shell[@class=&quot;ng-star-inserted&quot;]/cu-manager[@class=&quot;ng-tns-c809-3 ng-star-inserted&quot;]/div[@class=&quot;cu-manager2__container ng-tns-c809-3 ng-star-inserted layout-size_default&quot;]/div[@class=&quot;cu-manager2__container-inner ng-tns-c809-3&quot;]/div[@class=&quot;cu-manager2__router-outlet manager-space-bar ng-tns-c809-3&quot;]/cu-simple-bar[@class=&quot;cu-simple-bar cu-hidden-print ng-tns-c777-11 ng-tns-c809-3 ng-star-inserted&quot;]/div[@class=&quot;cu-simple-bar__container ng-tns-c777-11 ng-star-inserted&quot;]/div[@class=&quot;cu-simple-bar__body ng-tns-c777-11&quot;]/div[@class=&quot;cu-simple-bar__spaces ng-tns-c777-11&quot;]/cu2-project-list-bar[@class=&quot;cu2-project-list-bar ng-tns-c735-15 ng-tns-c777-11 ng-star-inserted&quot;]/div[@class=&quot;cu2-project-list-bar__body ng-tns-c735-15 ng-star-inserted&quot;]/cu-search-list[@class=&quot;cu-search-list ng-tns-c735-15 ng-star-inserted&quot;]/cu-search-input[@class=&quot;cu-search-input cu-search-list__input ng-star-inserted cu-search-input_active&quot;]/div[@class=&quot;cu-search-input__inner cu2-project-list-bar__search cu-search-input__inner_clear-active cu-search-input__inner_focused&quot;]/input[@class=&quot;cu-search-input__input ng-valid ng-touched ng-dirty&quot;]</value>
      <webElementGuid>01988e5a-37fb-4426-bbd5-094de7cdc25d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>aa126fc9-216d-4928-98c3-1cfcb1ec0cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-root[@id='app-root']/cu-app-shell/cu-manager/div/div/div[2]/cu-simple-bar/div/div[3]/div[7]/cu2-project-list-bar/div/cu-search-list/cu-search-input/div/input</value>
      <webElementGuid>ddf1c352-abf1-4491-ae40-b46091b5570d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>375317e9-3e1b-4783-9cc8-9bbaa90a58d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Filter Lists, Docs, &amp; Folders']</value>
      <webElementGuid>d5b0d3b4-7437-4b06-af13-e6320fae1b35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
