<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete task option</name>
   <tag></tag>
   <elementGuidId>12b92b9e-0d03-42f5-a71e-26f18642d253</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-14']/div/div[4]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.nav-menu-item.nav-menu-item__delete_task.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a9e6682e-fd6f-4fa7-bede-5e7b79fdd840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>533a6c3e-797f-4447-b522-b2d9fdc0bf75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-menu-item nav-menu-item__delete_task ng-star-inserted</value>
      <webElementGuid>533c77db-b685-4a2d-b957-fcc35978c863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>60df2385-4ef4-490d-92d3-86c726d75248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>109552db-8773-42e9-9997-a366e35af864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-14&quot;)/div[@class=&quot;cu-dropdown__menu nav-menu__controls ng-star-inserted cu-hidden-print cu-dropdown__menu_left cu-dropdown_open&quot;]/div[@class=&quot;nav-menu__group ng-star-inserted&quot;]/a[@class=&quot;nav-menu-item nav-menu-item__delete_task ng-star-inserted&quot;]</value>
      <webElementGuid>a5cb25ac-a258-48ee-86c7-e71609f72c4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-14']/div/div[4]/a[2]</value>
      <webElementGuid>c1e9f36d-ce48-42f6-85cd-668f35eb089f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Archive'])[1]/following::a[1]</value>
      <webElementGuid>713c694d-4ddc-4beb-9257-919a56fcc7d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Template Center'])[1]/following::a[2]</value>
      <webElementGuid>5530144c-8da3-4bc2-ad4c-14e38e720bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sharing &amp; Permissions'])[1]/preceding::a[1]</value>
      <webElementGuid>8c2aabe9-d4a2-4992-9765-ff91ddb2a0af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[9]</value>
      <webElementGuid>216d76a5-f355-4fdf-9ac2-9a4ef07ae374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[4]/a[2]</value>
      <webElementGuid>99c2989f-a454-44f3-a050-a68d32079faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>8300e591-0f2e-4af4-942e-60a675ba301f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
