<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>First TO-DO task status dropdown</name>
   <tag></tag>
   <elementGuidId>49ab3ab0-599f-4f4c-a247-611dc6c2b66e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Priority'])[2]/following::div[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cu-task-row-status__item.cu-task-row-status__item_light.cu-dropdown__toggle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f2d342c9-85a3-41d1-810c-426bab483f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>task-row-status__item</value>
      <webElementGuid>dbce864d-72fb-4f97-b3cd-2fa3adbfb570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltipmargin</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>46e70b93-76ed-4d9a-a262-c9236d2af352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cu-task-row-status__item cu-task-row-status__item_light cu-dropdown__toggle</value>
      <webElementGuid>e1f41f24-1262-4153-8cdc-0c24874080d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>49bf005c-54b8-41df-90a1-44c82e35543a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4a488b40-338e-4270-8706-007c2a6dfaa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Dropdown menu</value>
      <webElementGuid>e7ba139f-bb8e-45ea-8c7d-fe60f404c9e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>23241b8c-4d73-4844-9ee7-0ab05b53ec53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task-container-861mebt39&quot;)/div[@class=&quot;cu-task-row__main&quot;]/cu-task-row-status[@class=&quot;cu-task-row-status_dot cu-task-row-status&quot;]/div[@class=&quot;cu-dropdown ng-star-inserted&quot;]/div[@class=&quot;cu-task-row-status__item cu-task-row-status__item_light cu-dropdown__toggle&quot;]</value>
      <webElementGuid>2fa43ce9-3723-4beb-b424-613f3a488924</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='task-container-861mebt39']/div[2]/cu-task-row-status/div/div</value>
      <webElementGuid>b19d0384-e400-494e-abed-be02736b19ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priority'])[2]/following::div[11]</value>
      <webElementGuid>4b501ed0-e31f-40a5-b1f7-3cb8dd4f2f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Due date'])[2]/following::div[19]</value>
      <webElementGuid>e382cb5e-06c5-405e-b836-cde5db7583db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='asdsaas'])[1]/preceding::div[1]</value>
      <webElementGuid>789d449e-3622-480f-be94-2c051fe52d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change start and due dates'])[3]/preceding::div[25]</value>
      <webElementGuid>505454f1-6ccf-4519-88c5-30b5c1085d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//cu-task-list[2]/div/cu-task-row/div/div[2]/cu-task-row-status/div/div</value>
      <webElementGuid>3e862dbd-0d89-4379-8621-a003966cd7bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
