<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Task moved to trash modal</name>
   <tag></tag>
   <elementGuidId>1a2116fd-ef61-4911-95f5-d793a90b9d83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-root[@id='app-root']/cu-app-shell/cu-manager/cu-undo-toast-items/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.toast__undo.toast__undo_deleted.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6c09ff28-cd1a-4c80-b08a-2b7021a25533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>undo-toast-items__toast-undo</value>
      <webElementGuid>b1a2c0d6-4b7a-4adb-86f7-43d8555d720f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toast__undo toast__undo_deleted ng-star-inserted</value>
      <webElementGuid>50f2e4b5-d43c-4c5e-b92e-c5f740e3dea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Task   moved to trash Undo </value>
      <webElementGuid>c2b2075a-08ce-42ca-bbb1-d0fa611672d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/cu-app-shell[@class=&quot;ng-star-inserted&quot;]/cu-manager[@class=&quot;ng-tns-c750-3 ng-star-inserted&quot;]/cu-undo-toast-items[@class=&quot;toast cu-hidden-print ng-tns-c750-3 ng-star-inserted&quot;]/div[@class=&quot;toast__undo toast__undo_deleted ng-star-inserted&quot;]</value>
      <webElementGuid>72624943-0356-4a51-9d5a-8a1aa0147423</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-root[@id='app-root']/cu-app-shell/cu-manager/cu-undo-toast-items/div</value>
      <webElementGuid>965f88d8-7d73-40b8-9ca9-eba7aee6e072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculate'])[3]/following::div[9]</value>
      <webElementGuid>217daa8a-61e9-4044-af34-2ac0e2ea8d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priority'])[3]/following::div[27]</value>
      <webElementGuid>f4aaf037-5aaf-464b-836f-55ded7920a94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//cu-undo-toast-items/div</value>
      <webElementGuid>85a45d8e-c8df-45ea-bf9b-269c6264acec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Task   moved to trash Undo ' or . = ' Task   moved to trash Undo ')]</value>
      <webElementGuid>a5de8a0e-6ae2-475c-84eb-83707a559ac4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
