<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create Space_button</name>
   <tag></tag>
   <elementGuidId>26976dbb-26ba-4087-be85-9ee2669708df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.cu-btn.cu-btn_m.cu-create-project-modal__next.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-root[@id='app-root']/cu-modal-keeper/cu-modal/div/div[2]/div[2]/div[2]/cu-create-project-modal/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8e714a0a-ee6e-4bf5-b226-84f75e5d300f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>create-project-modal__next-step-all-good</value>
      <webElementGuid>300c2847-a84f-4796-bf1e-91ce54e87c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cu-btn cu-btn_m cu-create-project-modal__next ng-star-inserted</value>
      <webElementGuid>262c9c4e-37a0-4149-b046-c4a42fef5f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pendo</name>
      <type>Main</type>
      <value>create-project-modal__stage-summary</value>
      <webElementGuid>1bbfaca1-d495-46f4-a0eb-9c22e4b70b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Space</value>
      <webElementGuid>28cfa3c3-6cda-4895-bf55-1d2a6d4feb98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/cu-modal-keeper[1]/cu-modal[@class=&quot;ng-tns-c81-66 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c81-66 cu-modal cu-modal_md cu-modal__create-new-space cu-modal_open cu-modal_stop-open-animation&quot;]/div[@class=&quot;cu-modal__inner ng-tns-c81-66 ng-trigger ng-trigger-createTaskModalState&quot;]/div[@class=&quot;ng-tns-c81-66 cu-modal__dialog&quot;]/div[@class=&quot;ng-tns-c81-66 cu-modal__body cu-modal__body_no-min-height&quot;]/cu-create-project-modal[@class=&quot;cu-create-project-modal ng-tns-c809-3 ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/button[@class=&quot;cu-btn cu-btn_m cu-create-project-modal__next ng-star-inserted&quot;]</value>
      <webElementGuid>f0549815-c682-48e3-b53e-c304b1c7e01b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-root[@id='app-root']/cu-modal-keeper/cu-modal/div/div[2]/div[2]/div[2]/cu-create-project-modal/div/div/button</value>
      <webElementGuid>e4791585-2d50-463a-a065-fa346f76c719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default settings for views'])[1]/following::button[1]</value>
      <webElementGuid>3a1ff3d7-b59a-44dc-a4ad-24a2cac97529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ClickApps'])[1]/following::button[1]</value>
      <webElementGuid>7c775fa2-ea98-4080-b003-578bc8d899c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ClickUp is best experienced using our mobile app.'])[1]/preceding::button[1]</value>
      <webElementGuid>8738e546-95f1-4700-9bd2-516b867466ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Our web app has features so BIG, they won', &quot;'&quot;, 't fit on a small screen.')])[1]/preceding::button[1]</value>
      <webElementGuid>16fb5e8e-db15-4201-9946-b1ae947877b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create Space']/parent::*</value>
      <webElementGuid>90eaca34-c65b-49ba-b7d2-f4a75d450c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//cu-create-project-modal/div/div/button</value>
      <webElementGuid>0829fd35-9cdc-436b-bc1f-d310e0716d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Create Space' or . = 'Create Space')]</value>
      <webElementGuid>0b1af6da-f9ff-4445-bd00-8a51a3b9ef03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
