<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Enter space name_input field</name>
   <tag></tag>
   <elementGuidId>6bf60c54-74cb-4eab-a863-805f0860b446</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.cu-form__input.ng-untouched.ng-pristine.ng-invalid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>877735a2-9c0d-4dc6-9fc0-3364ce624cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>create-project-modal__form-input</value>
      <webElementGuid>74bd48b9-bf0a-4614-9187-92f6700f5748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>253b0a02-f9e4-43a0-973f-b373a090febe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Space na﻿me</value>
      <webElementGuid>e6a133f7-1b53-46b1-a08c-17eb6fe588e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cu-form__input ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>7db4e3bc-d2d3-49d1-a399-276d36c6f4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>f097346d-86fa-4459-85ed-e516eb9d320a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/cu-modal-keeper[1]/cu-modal[@class=&quot;ng-tns-c81-66 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c81-66 cu-modal cu-modal_md cu-modal__create-new-space cu-modal_open cu-modal_stop-open-animation&quot;]/div[@class=&quot;cu-modal__inner ng-tns-c81-66 ng-trigger ng-trigger-createTaskModalState&quot;]/div[@class=&quot;ng-tns-c81-66 cu-modal__dialog&quot;]/div[@class=&quot;ng-tns-c81-66 cu-modal__body cu-modal__body_no-min-height&quot;]/cu-create-project-modal[@class=&quot;cu-create-project-modal ng-tns-c809-3 ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;cu-form__row cu-create-project-modal__body ng-star-inserted&quot;]/div[@class=&quot;cu-form__field&quot;]/input[@class=&quot;cu-form__input ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>0d5d8f08-a32b-4249-b9d0-7cf50166d66b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[4]</value>
      <webElementGuid>23ab39ae-422b-48e4-be7f-e7f353d49a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-root[@id='app-root']/cu-modal-keeper/cu-modal/div/div[2]/div[2]/div[2]/cu-create-project-modal/div/div/div[3]/div[2]/input</value>
      <webElementGuid>d4b54757-a234-4049-9123-602ece3d1832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>ef4f067c-c9ad-442c-bc54-3e9946bb553f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Enter Space na﻿me']</value>
      <webElementGuid>7f7f713c-5f5a-4cb8-9e23-c23e43c49dc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
