<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Next_button</name>
   <tag></tag>
   <elementGuidId>fbed6a8a-d2ae-45a3-9090-d56b58c078d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.cu-btn.cu-btn_m.cu-create-project-modal__next.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-root[@id='app-root']/cu-modal-keeper/cu-modal/div/div[2]/div[2]/div[2]/cu-create-project-modal/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>40165a3b-b1a5-4ebe-bf68-17be33dfeefc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>create-project-modal__next-step-create-new-space</value>
      <webElementGuid>bbb2233d-1aca-4169-a260-fb754afe6f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cu-btn cu-btn_m cu-create-project-modal__next ng-star-inserted</value>
      <webElementGuid>67bb32b9-5fbe-46a6-9962-ef47ea82ec1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pendo</name>
      <type>Main</type>
      <value>create-project-modal__stage-name</value>
      <webElementGuid>19e206a6-b641-4343-b6e6-9afe0cbc4cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>988b58e8-8140-4c95-9c4a-a9d50796c371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/cu-modal-keeper[1]/cu-modal[@class=&quot;ng-tns-c81-66 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c81-66 cu-modal cu-modal_md cu-modal__create-new-space cu-modal_open cu-modal_stop-open-animation&quot;]/div[@class=&quot;cu-modal__inner ng-tns-c81-66 ng-trigger ng-trigger-createTaskModalState&quot;]/div[@class=&quot;ng-tns-c81-66 cu-modal__dialog&quot;]/div[@class=&quot;ng-tns-c81-66 cu-modal__body cu-modal__body_no-min-height&quot;]/cu-create-project-modal[@class=&quot;cu-create-project-modal ng-tns-c809-3 ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/button[@class=&quot;cu-btn cu-btn_m cu-create-project-modal__next ng-star-inserted&quot;]</value>
      <webElementGuid>e9bb0b4f-e21f-4f60-b5de-793eca3e55f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-root[@id='app-root']/cu-modal-keeper/cu-modal/div/div[2]/div[2]/div[2]/cu-create-project-modal/div/div/button</value>
      <webElementGuid>7dccfee8-bb8d-4bb0-aa9f-9bbe3deffb9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Space name'])[1]/following::button[1]</value>
      <webElementGuid>64d1e0f6-63d1-41ba-b6aa-d89a8eba1403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Templates'])[1]/following::button[1]</value>
      <webElementGuid>8878a583-6cae-4e62-b70a-90d4357e0149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ClickUp is best experienced using our mobile app.'])[1]/preceding::button[1]</value>
      <webElementGuid>e7cf416d-dc89-4543-a613-cf70d9bc4dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Our web app has features so BIG, they won', &quot;'&quot;, 't fit on a small screen.')])[1]/preceding::button[1]</value>
      <webElementGuid>f7194902-d0c0-4c4b-adbc-b988bd791e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>41bb1ac4-5432-47a7-ab4c-20fab1af9f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//cu-create-project-modal/div/div/button</value>
      <webElementGuid>7f28381e-289f-44a1-b89d-c9421c66194f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>bb56f949-e328-42db-a86a-d6781489e68a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
