<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Review Space_button</name>
   <tag></tag>
   <elementGuidId>24fab065-34d3-4b1e-8bfa-abd5c941dc31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.cu-btn.cu-btn_m.cu-create-project-modal__next.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-root[@id='app-root']/cu-modal-keeper/cu-modal/div/div[2]/div[2]/div[2]/cu-create-project-modal/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0357b5e1-7976-46e1-949f-b69029cabecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>create-project-modal__next-step-default-settings</value>
      <webElementGuid>b443d286-9782-4e32-bd71-bf4b7ce60cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cu-btn cu-btn_m cu-create-project-modal__next ng-star-inserted</value>
      <webElementGuid>07ea8727-9cc7-45da-90ee-199893a86eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pendo</name>
      <type>Main</type>
      <value>create-project-modal__stage-views</value>
      <webElementGuid>ac405778-e929-476a-8a90-7c5355377e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Review Space</value>
      <webElementGuid>e8a6d715-20c4-4705-871c-ca2a49e573de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/cu-modal-keeper[1]/cu-modal[@class=&quot;ng-tns-c81-66 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c81-66 cu-modal cu-modal_md cu-modal__create-new-space cu-modal_open cu-modal_stop-open-animation&quot;]/div[@class=&quot;cu-modal__inner ng-tns-c81-66 ng-trigger ng-trigger-createTaskModalState&quot;]/div[@class=&quot;ng-tns-c81-66 cu-modal__dialog&quot;]/div[@class=&quot;ng-tns-c81-66 cu-modal__body cu-modal__body_no-min-height&quot;]/cu-create-project-modal[@class=&quot;cu-create-project-modal ng-tns-c809-3 ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/button[@class=&quot;cu-btn cu-btn_m cu-create-project-modal__next ng-star-inserted&quot;]</value>
      <webElementGuid>685512f1-ba5a-4572-a50e-ddaf1a84124c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-root[@id='app-root']/cu-modal-keeper/cu-modal/div/div[2]/div[2]/div[2]/cu-create-project-modal/div/div/button</value>
      <webElementGuid>a1c83624-e6b4-4ada-a61f-25d9b54afe5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workload'])[1]/following::button[1]</value>
      <webElementGuid>b78d39c9-fd2e-4692-ad26-0921ba1b5602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Timeline'])[1]/following::button[1]</value>
      <webElementGuid>fddd3f5e-9aba-429f-aa5e-9f2e7a5f64f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ClickUp is best experienced using our mobile app.'])[1]/preceding::button[1]</value>
      <webElementGuid>026f55cc-d40f-4ab1-8108-077e54b69749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Our web app has features so BIG, they won', &quot;'&quot;, 't fit on a small screen.')])[1]/preceding::button[1]</value>
      <webElementGuid>821e9cfe-e790-45cd-bad2-888a5be180ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Review Space']/parent::*</value>
      <webElementGuid>1022d7c1-0255-4c8c-b344-0f31233efdfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//cu-create-project-modal/div/div/button</value>
      <webElementGuid>1003f335-91af-469c-bf96-d838059c9b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Review Space' or . = 'Review Space')]</value>
      <webElementGuid>66b27221-0e02-4b72-be4a-40f81a03f649</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
